### ISSUE TITLE
enc_ans.cc:228: JXL_DASSERT: n <= 255

### ISSUE THREAD

**Issue by y-guyon** [inflation/jpegxl-rs#101]
Hello, I got the following failure:

`cargo test`
```
running 1 test
./lib/jxl/enc_ans.cc:228: JXL_DASSERT: n <= 255
error: test failed, to rerun pass `--bin reprojxl`
```

with the following repro project:

`Cargo.toml`
```toml
[package]
name = "reprojxl"
version = "0.1.0"
edition = "2021"

[dependencies]
jpegxl-sys = { version = "=0.11.1" }
jpegxl-rs = { version = "=0.11.1", features = ["vendored"] }
```

`main.rs`
```rs
fn main() {}

#[test]
fn encode() {
    let width = 1;
    let height = 1;
    let pixels: &[u16] = &[1020u16];

    let mut encoder_builder = jpegxl_rs::encoder_builder();
    encoder_builder.has_alpha(false);
    encoder_builder.lossless(true);
    encoder_builder.uses_original_profile(true);
    encoder_builder.color_encoding(jpegxl_rs::encode::ColorEncoding::SrgbLuma);
    encoder_builder.speed(jpegxl_rs::encode::EncoderSpeed::Kitten);
    encoder_builder
        .build()
        .unwrap()
        .encode_frame::<u16, u16>(
            &jpegxl_rs::encode::EncoderFrame::new(pixels)
                .num_channels(1)
                .endianness(jpegxl_rs::Endianness::Native)
                .align(0),
            width,
            height,
        )
        .unwrap();
}
```

I was not able to reproduce with a CMake-built libjxl:
```sh
git clone -b v0.11.0 --depth 1 https://github.com/libjxl/libjxl.git
cd libjxl
./deps.sh
cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
cmake --build build --parallel
build/tools/cjxl 1x1_u16.png 1x1_u16.jxl -e 8
# Works fine but maybe PNG is not read as 16-bit monochrome
```
This is why I am filing an issue here.
